### ISSUE TITLE
kill with region selected

### ISSUE THREAD

**Issue by tjaartvdwalt** [TLINDEN/viking-mode#2]
First off, cool plugin!

Ideally I would like to use it as a `kill-line` replacement, binding it to `C-k`, so that I don't have to remember yet another kill shortcut.

Currently there is one use case that is a dealbreaker for me:
If I have a selected region I would like to kill that region instead of using the viking-mode algorithm to select the region. 

Does that sound like something that might be useful to implement? Maybe as an option?

**Comment by tjaartvdwalt** [comment]
Actually now after playing around with it some more I realise that when I have a region selected, I use `kill-region` instead of `kill-line` in any case, so it does not really make sense... sorry for the bother

**Comment by TLINDEN** [comment]
Well, I already had a similar idea. There maybe two variants: a) if there's a region, just delete it. b) if there's a region, act only inside, so the last action would not kill the buffer but only the region.

On the other side, if I have a region marked and decide to delete it, I just hit <backspace> and away it is.

So, I'm undecided...

**Comment by tjaartvdwalt** [comment]
Yes, after thinking about it, hitting `C-w` or delete/backspace on the region should be good enough.

When I first created the issue I thought `kill-line` with a selected region would kill the region, but after testing I realized it does not behave like that.
