### ISSUE TITLE
inconsistent kill word

### ISSUE THREAD

**Issue by jack99999** [TLINDEN/viking-mode#3]
hi

when i press C-d the first time, the current word is deleted... but if the cursor is on the first character of the word then the previous word is deleted. 

i never want to delete the previous word... is there a way to customise viking-mode so that it never deletes the previous word?

thanks

jack

**Comment by TLINDEN** [comment]
No, this is a bug. It shall delete the word at point, not the one before. I'll take a look into it.
- Tom

**Comment by TLINDEN** [comment]
Ok, fixed in 233d45b. Thanks for reporting.
- Tom

**Comment by jack99999** [comment]
super! that's fixed it, many thanks.

i now see something that you might like to consider... if you put the cursor in space and C-d, you clear spaces. the next C-d then kills line right. thus, there is no way to delete the word. perhaps clear spaces and then kill word instead?

jack

**Comment by TLINDEN** [comment]
Hello Jack,

good point. In fact I had it already on my TODO list but forgot it...

In order for this to be possible I had to change a couple of things here and there. It now deletes the word at point after whitespace-deletion, as suggested. As a side effect it is now possible to modify the list of functions to be called in a row, the variable is `viking-kill-funcs`, which is customizable. This is the default setting:

```
(list 'viking-kill-word 'viking-kill-line-from-point
       'viking-kill-line 'viking-kill-paragraph 'viking-kill-buffer)
```

Diff:  d80c032.
- Tom

**Comment by jack99999** [comment]
hi tom. that works beautifully. and i'm sure i could have fun with the customisable list!

many thanks

jack
