### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by jdahm** [TLINDEN/viking-mode#6]
I've been playing around with this mode and really like it. I want to use it, but at the moment it feels sluggish. For instance, I can actually see the region highlighted for a few tenths of a second before the kill. I don't need to see that, and would rather it just be instantaneous. Is there an option not to see that? Are there plans or ideas to overall speed it up?

I would help with this but have been busy with my own work lately.

**Comment by TLINDEN** [comment]
Yes good point, I need to add a way to disable this.

Meanwhile however you could try this:

```
(setq viking-blink-time 0)
```

Of course it will still call the function and blink but it will only last 0 seconds.

**Comment by TLINDEN** [comment]
I added a new flag in commit 31c4a4f which you can use to disable blinking: `(setq viking-enable-blinking nil)`.
