### ISSUE TITLE
enhancement suggestion: kill-char on first invocation

### ISSUE THREAD

**Issue by abrochard** [TLINDEN/viking-mode#8]
Hi,

I like viking-mode, but I also like to just delete a char on the first invocation, a bit like the regular C-d.
I created a new function to kill the character on point, and with the proper setq, it gets added to the list of functions. Tried my best to respect the other customization.

May I send a pull request if you are interested?

Fyi, lisp is really not my specialty.
Thanks,
Adrien

**Comment by TLINDEN** [comment]
But there's `delete-char`already, you don't really need an extra function for this. So you just put `delete-char`as first entry into `viking-kill-functions` and there you go.

best,
Tom

**Comment by abrochard** [comment]
Hmm. I tempered with that at first, but there are two issues I found:

_`delete-char` actually deletes instead of saving to the kill-ring. So if you C-d C-d and then C-y, you are getting the full word back minus the character that you were on.
_if `viking-enable-region-kill` is set, the first C-d will not kill the region.

Are there easy workarounds for this?
Thanks,
Adrien

**Comment by TLINDEN** [comment]
What about

```
(setq viking-kill-functions (list '(lambda() (delete-char 1 t))
                                  'viking-kill-word
                                  'viking-kill-line-from-point
                                  'viking-kill-line
                                  'viking-kill-paragraph
                                  'viking-kill-buffer))
```

?

**Comment by abrochard** [comment]
Sweet. Just to make sure the char is at the correct position in the kill-ring I made a few adjustments.

```
(setq viking-kill-functions (list '(lambda() (delete-char 1 t))
                                  '(lambda()
                                     (insert (pop kill-ring)) ;; insert the char back
                                     (kill-new "") ;; start a new entry in the kill-ring
                                     (viking-kill-word)
                                     (kill-append " " nil)) ;; append the extra space
                                  'viking-kill-line-from-point
                                  'viking-kill-line
                                  'viking-kill-paragraph
                                  'viking-kill-buffer))
```

Thanks a lot!
Adrien
